// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://yyqfydjojnbyenocexem.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cWZ5ZGpvam5ieWVub2NleGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE3NzQxNTMsImV4cCI6MjA0NzM1MDE1M30.VoHZ5NKGAkABhn7kNK0B1B-BUl3h84Eij-dM47DGp-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);